import { LawEnforcement, Medical } from "@/lib/schema/incident";

export const IncidentReportHeaders = {
  NewIncidentReport: "New Incident Report",
  location: "location",
  EventAndFillerInformation: "Event & Person Filling out Form Information",
  show: "Show/Event",
  wearsGlasses: "Do you wear GLASSES or LENSES?",
  inUse: "Were they in use?",
  severity: "severity",
  PatronInformation: "Patron Information",
  patronName: "Patron Name",
  patronPhone: "Patron Phone",
  patronEmail: "Patron Email",
  patronAddress: "Patron Address",
  patronCityState: "Patron City/State",
  patronContactTime: "Best Contact Time",
  witnesses: "Witnesses",
  WitnessInformation: "Witness Information",
  employmentType: "Employment Type",
  witnessEmail: "Email",
  witnessName: "Full Name",
  witnessPhone: "Phone",
  witnessContactTime: "Best Contact Time",
  Witness: "Witness",
  MedicalInformation: "Medical Information",
  VisibleInjuries: "Were there visible injuries?",
  VisibleInjuriesExplain: "EXPLAIN:",
  MedicalAttention: "Was the need for medical attention apparent?",
  medicalServiceOffered: "Were medical services offered?",
  medicalAccepted: "Were they ACCEPTED or REFUSED?",
  ambulanceRequested: "Was an ambulance requested?",
  ambulanceCompany: "Company",
  ambulanceEMT: "EMT Name or Number",
  didPatientLeaveAmbulance: "Did patient leave in the ambulance?",
  whereTheyGo: "If not, where did they go?",
  LawEnforcement: "Law Enforcement Information",
  contacted: "Was law enforcement contacted?",
  explanation: "EXPLAIN:",
  reportWritten: "Was a police report written?",
  reportNumber: "Report Number",
  citation: "CITATION # or CHARGE/ARREST:",
  officerName: "Officer Name & Badge #:",
};

export const defaultMedical: Medical = {
  visible_injuries: true,
  injury_explanation: "",
  medical_attention_apparent: true,
  medical_services_offered: true,
  medical_services_accepted: true,
  ambulance_requested: true,
  ambulance_company: "",
  emt_name_or_number: "",
  patron_left_in_ambulance: true,
  destination: "",
};

export const defaultLaw: LawEnforcement = {
  law_enforcement_contacted: true,
  contact_explanation: "",
  police_report_written: true,
  police_report_number: "",
  citation_or_charge_or_arrest: "",
  officer_name_badge: "",
};
