export const shows = [
  "Main Stage",
  "Side Stage",
  "Bar Left",
  "Bar Right",
  "VIP Area",
  "General Admission",
  "Outdoor Area",
];

export const witnessTypes = ["employee", "non employee"];

export const IncidentReportHeaders = {
  NewIncidentReport: "New Incident Report",
  MandatoryInformation: "Mandatory Information",
  show: "Show/Event",
  wearsGlasses: "Do you wear GLASSES or LENSES?",
  inUse: "Were they in use?",
  PatronInformation: "Patron Information",
  patronName: "Patron Name",
  patronPhone: "Patron Phone",
  patronEmail: "Patron Email",
  patronAddress: "Patron Address",
  patronCityState: "Patron City/State",
  patronContactTime: "Best Contact Time",
  witnesses: "Witnesses",
  WitnessInformation: "Witness Information",
  employmentType: "Employment Type",
  witnessEmail: "Email",
  witnessName: "Full Name",
  witnessPhone: "Phone",
  witnessContactTime: "Best Contact Time",
  Witness: "Witness",
  MedicalInformation: "Medical Information",
  VisibleInjuries: "Were there visible injuries?",
  VisibleInjuriesExplain: "EXPLAIN:",
  MedicalAttention: "Was the need for medical attention apparent?",
  medicalServiceOffered: "Were medical services offered?",
  medicalAccepted: "Were they ACCEPTED or REFUSED?",
  ambulanceRequested: "Was an ambulance requested?",
  ambulanceCompany: "Company",
  ambulanceEMT: "EMT Name or Number",
  didPatientLeaveAmbulance: "Did patient leave in the ambulance?",
  whereTheyGo: "If not, where did they go?",
  LawEnforcement: "Law Enforcement Information",
  contacted: "Was law enforcement contacted?",
  explanation: "EXPLAIN:",
  reportWritten: "Was a police report written?",
  reportNumber: "Report Number",
  citation: "CITATION # or CHARGE/ARREST:",
  officerName: "Officer Name & Badge #:",
};
