import { LawEnforcement, Medical } from "@/lib/schema/incident";

export const witnessTypes = ["employee", "non employee"];

export const IncidentReportHeaders = {
  NewIncidentReport: "New Incident Report",
  EventAndFillerInformation: "Event & Person Filling out Form Information",
  show: "Show/Event",
  wearsGlasses: "Do you wear GLASSES or LENSES?",
  inUse: "Were they in use?",
  severity: "severity",
  PatronInformation: "Patron Information",
  patronName: "Patron Name",
  patronPhone: "Patron Phone",
  patronEmail: "Patron Email",
  patronAddress: "Patron Address",
  patronCityState: "Patron City/State",
  patronContactTime: "Best Contact Time",
  witnesses: "Witnesses",
  WitnessInformation: "Witness Information",
  employmentType: "Employment Type",
  witnessEmail: "Email",
  witnessName: "Full Name",
  witnessPhone: "Phone",
  witnessContactTime: "Best Contact Time",
  Witness: "Witness",
  MedicalInformation: "Medical Information",
  VisibleInjuries: "Were there visible injuries?",
  VisibleInjuriesExplain: "EXPLAIN:",
  MedicalAttention: "Was the need for medical attention apparent?",
  medicalServiceOffered: "Were medical services offered?",
  medicalAccepted: "Were they ACCEPTED or REFUSED?",
  ambulanceRequested: "Was an ambulance requested?",
  ambulanceCompany: "Company",
  ambulanceEMT: "EMT Name or Number",
  didPatientLeaveAmbulance: "Did patient leave in the ambulance?",
  whereTheyGo: "If not, where did they go?",
  LawEnforcement: "Law Enforcement Information",
  contacted: "Was law enforcement contacted?",
  explanation: "EXPLAIN:",
  reportWritten: "Was a police report written?",
  reportNumber: "Report Number",
  citation: "CITATION # or CHARGE/ARREST:",
  officerName: "Officer Name & Badge #:",
};

export const defaultMedical: Medical = {
  visibleInjuries: "yes",
  visibleInjuriesExplain: "",
  medicalAttention: "yes",
  offeredMedical: "yes",
  accepted: "accepted",
  ambulanceRequested: "no",
  ambulanceCompany: "",
  ambulanceEMT: "",
  didPatientLeaveAmbulance: "yes",
  whereTheyGo: "",
};

export const defaultLaw: LawEnforcement = {
  contacted: "yes",
  explanation: "",
  reportWritten: "no",
  reportNumber: "",
  citation: "",
  officerName: "",
};
